stages:
  - docker-hub

jobs:
  include:

    - stage: docker-hub
      services:
        - docker
      env:
        - IMAGE_NAME=felippemauricio/awscli-dind
      script:
        - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
        - docker build -t $IMAGE_NAME .
        - docker push "$IMAGE_NAME"
      on:
        branch: master
