stages:
  - docker-hub

jobs:
  include:

    - stage: docker-hub
      services:
        - docker
      env:
        - IMAGE_NAME=felippemauricio/awscli-dind
      script:
        - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
        - docker build -t $IMAGE_NAME .
        - export IMAGE_NAME_VERSION_1="$IMAGE_NAME:$TRAVIS_COMMIT"
        - echo $IMAGE_NAME_VERSION_1
        - docker tag $IMAGE_NAME $IMAGE_NAME_VERSION_1
        - docker push IMAGE_NAME_VERSION_1
        - export IMAGE_NAME_VERSION_2="$IMAGE_NAME:latest"
        - echo $IMAGE_NAME_VERSION_2
        - docker tag $IMAGE_NAME $IMAGE_NAME_VERSION_2
        - docker push $IMAGE_NAME_VERSION_2
      on:
        branch: master